---
kind: pipeline
type: docker
name: build_image

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: haylinmoore/drone-rollout-restart
    tags: latest
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
